from typing import Any

e: float
inf: float
nan: float
pi: float
tau: float

def acos(*args, **kwargs): ...
def acosh(*args, **kwargs): ...
def asin(*args, **kwargs): ...
def asinh(*args, **kwargs): ...
def atan(*args, **kwargs): ...
def atan2(*args, **kwargs): ...
def atanh(*args, **kwargs): ...
def cbrt(*args, **kwargs): ...
def ceil(*args, **kwargs): ...
def comb(*args, **kwargs): ...
def copysign(*args, **kwargs): ...
def cos(*args, **kwargs): ...
def cosh(*args, **kwargs): ...
def degrees(*args, **kwargs): ...
def dist(*args, **kwargs): ...
def erf(*args, **kwargs): ...
def erfc(*args, **kwargs): ...
def exp(*args, **kwargs): ...
def exp2(*args, **kwargs): ...
def expm1(*args, **kwargs): ...
def fabs(*args, **kwargs): ...
def factorial(*args, **kwargs): ...
def floor(*args, **kwargs): ...
def fmod(x, y) -> Any: ...
def frexp(*args, **kwargs): ...
def fsum(*args, **kwargs): ...
def gamma(*args, **kwargs): ...
def gcd(*args, **kwargs): ...
def hypot(*coordinates) -> value: ...
def isclose(*args, **kwargs): ...
def isfinite(*args, **kwargs): ...
def isinf(*args, **kwargs): ...
def isnan(*args, **kwargs): ...
def isqrt(*args, **kwargs): ...
def lcm(*args, **kwargs): ...
def ldexp(*args, **kwargs): ...
def lgamma(*args, **kwargs): ...
def log(*args, **kwargs): ...
def log10(*args, **kwargs): ...
def log1p(*args, **kwargs): ...
def log2(*args, **kwargs): ...
def modf(*args, **kwargs): ...
def nextafter(*args, **kwargs): ...
def perm(*args, **kwargs): ...
def pow(*args, **kwargs): ...
def prod(*args, **kwargs): ...
def radians(*args, **kwargs): ...
def remainder(*args, **kwargs): ...
def sin(*args, **kwargs): ...
def sinh(*args, **kwargs): ...
def sqrt(*args, **kwargs): ...
def sumprod(*args, **kwargs): ...
def tan(*args, **kwargs): ...
def tanh(*args, **kwargs): ...
def trunc(*args, **kwargs): ...
def ulp(*args, **kwargs): ...
