[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pcstubgen"
version = "0.1.0"
description = "Generate Python stubs for modules."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "libclang>=18.1.1",
    "loguru>=0.7.3",
    "typer>=0.24.1",
]

[project.scripts]
pcstubgen = "pcstubgen.__main__:app"

[dependency-groups]
dev = [
    "dask>=2026.3.0",
    "hypothesis>=6.151.10",
    "marray>=0.0.12",
    "matplotlib>=3.10.8",
    "mypy>=1.20.0",
    "numba>=0.65.0",
    "numpy>=2.4.4",
    "olefile>=0.47",
    "pandas>=3.0.2",
    "pillow>=12.1.1",
    "pooch>=1.9.0",
    "psycopg2>=2.9.11",
    "pyarrow>=23.0.1",
    "pybind11-stubgen>=2.5.5",
    "pytest>=9.0.2",
    "requests>=2.33.1",
    "scipy>=1.17.1",
    "setuptools>=81.0.0",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
]
