from __future__ import annotations

from .....type_models import AnyType, DictType, ListType, RawType, Type, UnionType


PY_ARG_PARSE_TYPE_OBJECT_NAME_TO_TYPE: dict[str, Type] = {
    "PyList_Type": RawType("list"),
    "PyTuple_Type": RawType("tuple"),
    "PyDict_Type": RawType("dict"),
    "PyUnicode_Type": RawType.str_,
    "PyLong_Type": RawType.int_,
    "PyFloat_Type": RawType.float_,
    "PyBool_Type": RawType.bool_,
    "PyBytes_Type": RawType.bytes_,
    "PyByteArray_Type": RawType.bytearray_,
    "PySet_Type": RawType("set"),
    "PyFrozenSet_Type": RawType("frozenset"),
    "PyType_Type": RawType("type"),
    "PyBaseObject_Type": RawType.object_,
    "PyDateTimeAPI->DateType": RawType("datetime.date", imports=("datetime",)),
    "PyDateTimeAPI->TimeType": RawType("datetime.time", imports=("datetime",)),
    "PyDateTimeAPI->DateTimeType": RawType("datetime.datetime", imports=("datetime",)),
    "PyDateTimeAPI->DeltaType": RawType("datetime.timedelta", imports=("datetime",)),
}

PY_ARG_PARSE_CONVERTER_NAME_TO_TYPE: dict[str, Type] = {}

OBJECT_NAME_TO_TYPE: dict[str, Type] = {
    "_Py_NoneStruct": RawType.none_,
    "_Py_TrueStruct": RawType.bool_,
    "_Py_FalseStruct": RawType.bool_,
}

_ERROR_RETURN_TYPE = UnionType(())

ERROR_RETURN_FUNCTION_NAME_TO_TYPE: dict[str, Type] = {
    "PyErr_Format": _ERROR_RETURN_TYPE,
    "PyErr_FormatV": _ERROR_RETURN_TYPE,
    "PyErr_NoMemory": _ERROR_RETURN_TYPE,
    "PyErr_SetFromErrno": _ERROR_RETURN_TYPE,
    "PyErr_SetFromErrnoWithFilenameObject": _ERROR_RETURN_TYPE,
    "PyErr_SetFromErrnoWithFilenameObjects": _ERROR_RETURN_TYPE,
    "PyErr_SetFromErrnoWithFilename": _ERROR_RETURN_TYPE,
    "PyErr_SetFromWindowsErr": _ERROR_RETURN_TYPE,
    "PyErr_SetFromWindowsErrWithFilename": _ERROR_RETURN_TYPE,
    "PyErr_SetExcFromWindowsErr": _ERROR_RETURN_TYPE,
    "PyErr_SetExcFromWindowsErrWithFilenameObject": _ERROR_RETURN_TYPE,
    "PyErr_SetExcFromWindowsErrWithFilenameObjects": _ERROR_RETURN_TYPE,
    "PyErr_SetExcFromWindowsErrWithFilename": _ERROR_RETURN_TYPE,
    "PyErr_SetImportError": _ERROR_RETURN_TYPE,
    "PyErr_SetImportErrorSubclass": _ERROR_RETURN_TYPE,
}

_TUPLE_ANY_TYPE = RawType("tuple[typing.Any, ...]", imports=("typing",))
_LIST_ANY_TYPE = ListType(AnyType())
_DICT_ANY_TYPE = DictType(AnyType(), AnyType())
_SET_ANY_TYPE = RawType("set[typing.Any]", imports=("typing",))

CHECK_MACRO_NAME_TO_TYPE: dict[str, Type] = {
    "PyTuple_Check": _TUPLE_ANY_TYPE,
    "PyTuple_CheckExact": _TUPLE_ANY_TYPE,
    "PyList_Check": _LIST_ANY_TYPE,
    "PyList_CheckExact": _LIST_ANY_TYPE,
    "PyUnicode_Check": RawType.str_,
    "PyUnicode_CheckExact": RawType.str_,
    "PyBytes_Check": RawType.bytes_,
    "PyBytes_CheckExact": RawType.bytes_,
    "PyDict_Check": _DICT_ANY_TYPE,
    "PyDict_CheckExact": _DICT_ANY_TYPE,
    "PySet_Check": _SET_ANY_TYPE,
    "PySet_CheckExact": _SET_ANY_TYPE,
    "PyLong_Check": RawType.int_,
    "PyLong_CheckExact": RawType.int_,
    "PyFloat_Check": RawType.float_,
    "PyFloat_CheckExact": RawType.float_,
    "PyBool_Check": RawType.bool_,
}

CALL_NAME_TO_TYPE: dict[str, Type] = {
    **ERROR_RETURN_FUNCTION_NAME_TO_TYPE,
    "PyCapsule_New": RawType("types.CapsuleType", imports=("types",)),
    "Py_GenericAlias": RawType("types.GenericAlias", imports=("types",)),
    "PyBool_FromLong": RawType.bool_,
    "PyLong_FromLong": RawType.int_,
    "PyLong_FromUnsignedLong": RawType.int_,
    "PyLong_FromSsize_t": RawType.int_,
    "PyLong_FromSize_t": RawType.int_,
    "PyLong_FromLongLong": RawType.int_,
    "PyLong_FromUnsignedLongLong": RawType.int_,
    "PyLong_FromDouble": RawType.int_,
    "PyLong_FromString": RawType.int_,
    "PyLong_FromUnicodeObject": RawType.int_,
    "PyLong_FromVoidPtr": RawType.int_,
    "PyFloat_FromString": RawType.float_,
    "PyFloat_FromDouble": RawType.float_,
    "PyComplex_FromCComplex": RawType.complex_,
    "PyComplex_FromDoubles": RawType.complex_,
    "PyUnicode_New": RawType.str_,
    "PyUnicode_FromKindAndData": RawType.str_,
    "PyUnicode_FromString": RawType.str_,
    "PyUnicode_FromStringAndSize": RawType.str_,
    "PyUnicode_FromFormat": RawType.str_,
    "PyUnicode_FromFormatV": RawType.str_,
    "PyUnicode_FromObject": RawType.str_,
    "PyUnicode_FromEncodedObject": RawType.str_,
    "PyUnicode_FromWideChar": RawType.str_,
    "PyUnicode_Decode": RawType.str_,
    "PyUnicode_DecodeUTF8": RawType.str_,
    "PyUnicode_DecodeUTF8Stateful": RawType.str_,
    "PyUnicode_DecodeUTF32": RawType.str_,
    "PyUnicode_DecodeUTF32Stateful": RawType.str_,
    "PyUnicode_DecodeUTF16": RawType.str_,
    "PyUnicode_DecodeUTF16Stateful": RawType.str_,
    "PyUnicode_DecodeUTF7": RawType.str_,
    "PyUnicode_DecodeUTF7Stateful": RawType.str_,
    "PyUnicode_DecodeUnicodeEscape": RawType.str_,
    "PyUnicode_DecodeRawUnicodeEscape": RawType.str_,
    "PyUnicode_DecodeLatin1": RawType.str_,
    "PyUnicode_DecodeASCII": RawType.str_,
    "PyUnicode_DecodeCharmap": RawType.str_,
    "PyUnicode_DecodeLocaleAndSize": RawType.str_,
    "PyUnicode_DecodeLocale": RawType.str_,
    "PyUnicode_DecodeFSDefaultAndSize": RawType.str_,
    "PyUnicode_DecodeFSDefault": RawType.str_,
    "PyUnicode_Translate": RawType.str_,
    "PyUnicode_DecodeMBCS": RawType.str_,
    "PyUnicode_DecodeMBCSStateful": RawType.str_,
    "PyUnicode_DecodeCodePageStateful": RawType.str_,
    "PyUnicode_Substring": RawType.str_,
    "PyUnicode_Concat": RawType.str_,
    "PyUnicode_Join": RawType.str_,
    "PyUnicode_Replace": RawType.str_,
    "PyUnicode_Format": RawType.str_,
    "PyUnicode_InternFromString": RawType.str_,
    "PyBytes_FromString": RawType.bytes_,
    "PyBytes_FromStringAndSize": RawType.bytes_,
    "PyBytes_FromFormat": RawType.bytes_,
    "PyBytes_FromFormatV": RawType.bytes_,
    "PyBytes_FromObject": RawType.bytes_,
    "PyUnicode_AsEncodedString": RawType.bytes_,
    "PyUnicode_AsUTF8String": RawType.bytes_,
    "PyUnicode_AsUTF32String": RawType.bytes_,
    "PyUnicode_AsUTF16String": RawType.bytes_,
    "PyUnicode_AsUnicodeEscapeString": RawType.bytes_,
    "PyUnicode_AsRawUnicodeEscapeString": RawType.bytes_,
    "PyUnicode_AsLatin1String": RawType.bytes_,
    "PyUnicode_AsASCIIString": RawType.bytes_,
    "PyUnicode_AsCharmapString": RawType.bytes_,
    "PyUnicode_EncodeLocale": RawType.bytes_,
    "PyUnicode_EncodeFSDefault": RawType.bytes_,
    "PyUnicode_AsMBCSString": RawType.bytes_,
    "PyUnicode_EncodeCodePage": RawType.bytes_,
    "PyByteArray_FromObject": RawType.bytearray_,
    "PyByteArray_FromStringAndSize": RawType.bytearray_,
    "PyByteArray_Concat": RawType.bytearray_,
    "PySlice_New": RawType.slice_,
    "PyMemoryView_FromObject": RawType.memoryview_,
    "PyMemoryView_FromMemory": RawType.memoryview_,
    "PyMemoryView_FromBuffer": RawType.memoryview_,
    "PyMemoryView_GetContiguous": RawType.memoryview_,
    "PyTuple_New": RawType("tuple"),
    "PyTuple_Pack": RawType("tuple"),
    "PyTuple_GetSlice": RawType("tuple"),
    "PyList_AsTuple": RawType("tuple"),
    "PyUnicode_Partition": RawType("tuple"),
    "PyUnicode_RPartition": RawType("tuple"),
    "PyList_New": RawType("list"),
    "PyList_GetSlice": RawType("list"),
    "PyUnicode_Split": RawType("list"),
    "PyUnicode_RSplit": RawType("list"),
    "PyUnicode_Splitlines": RawType("list"),
    "PyDict_Items": RawType("list"),
    "PyDict_Keys": RawType("list"),
    "PyDict_Values": RawType("list"),
    "PyDict_New": RawType("dict"),
    "PyDict_Copy": RawType("dict"),
    "PySet_New": RawType("set"),
    "PyFrozenSet_New": RawType("frozenset"),
}
